'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DIFFICULTY={easy:{min:6,max:7,rate:.82,pause:650,pools:['easy','normal']},normal:{min:5,max:6,rate:1,pause:480,pools:['easy','normal','hard']},hard:{min:3,max:4,rate:1.18,pause:300,pools:['normal','hard']}};
const EASY='Chair,Mug,Fork,Spoon,Plate,Bowl,Cup,Glass,Wallet,Key,Toothbrush,Toothpaste,Backpack,Umbrella,Notebook,Pen,Pencil,Eraser,Ruler,Scissors,Tape,Glue Stick,Folder,Book,Bookmark,Clock,Watch,Mirror,Comb,Hairbrush,Soap,Towel,Shirt,Sock,Shoe,Hat,Cap,Belt,Bag,Phone,Laptop,Mouse,Keyboard,Charger,Remote Control,Water Bottle,Lunch Box,Kettle,Pan,Pot,Knife,Cutting Board,Pillow,Blanket,Lamp,Candle,Vase,Broom,Mop,Bucket,Basket,Trash Can'.split(',');
const NORMAL='Headphones,Earbuds,Speaker,Stapler,Highlighter,Marker,Clipboard,Binder,Sticky Note,Paper Clip,Binder Clip,Calculator,Desk Lamp,Printer,USB Drive,Power Bank,Extension Cord,Webcam,Router,Hairdryer,Razor,Shampoo Bottle,Lotion Bottle,Sunscreen,Nail Clipper,Tissue Box,Hand Sanitiser,Medicine Bottle,Pill Box,Clothes Hanger,Iron,Laundry Basket,Detergent Bottle,Sunglasses,Suitcase,Travel Pillow,Passport,Luggage Tag,Thermos,Food Container,Jar,Milk Carton,Cereal Box,Egg Carton,Tea Bag,Coffee Filter,Teapot,Spatula,Tongs,Ladle,Whisk,Peeler,Grater,Measuring Cup,Oven Mitt,Apron,Dish Sponge,Tray,Coaster,Picture Frame,Plant Pot,Whiteboard,File Tray,Mouse Pad,Flashlight,Battery,Light Bulb,Screwdriver,Hammer,Wrench,Pliers,Tape Measure,Toolbox,Garden Hose,Watering Can,Trowel,Rake,Shovel,Yoga Mat,Dumbbell,Jump Rope,Helmet,Swim Goggles,Cooler,Ice Pack,Reusable Bag,Makeup Brush,Lip Balm,Cotton Pad,Wet Wipes,Bandage,Door Stop,Curtain,Storage Box,Photo Album,Game Controller,Fan,Air Purifier,Scale,Sewing Kit,Safety Pin,Packing Cube,Travel Adapter,Index Card,Pen Cup,Bookend,Hole Punch,Correction Tape,Receipt,Gift Bag,Ribbon,Greeting Card,Postcard,Stamp,Lanyard,Hand Fan,Reusable Straw,Chopsticks,Rice Paddle,Ice Cube Tray,Foil Roll,Baking Tray,Blender,Toaster,Rice Cooker,Microwave,Air Fryer,Salt Shaker,Spice Jar,Honey Jar,Butter Dish'.split(',');
const HARD='Colander,Lint Roller,Staple Remover,Cable Organiser,Garlic Press,Shoehorn,Strainer,Can Opener,Bottle Opener,Corkscrew,Potato Masher,Kitchen Scale,Salad Spinner,Lemon Squeezer,French Press,Coffee Grinder,Pepper Grinder,Oil Bottle,Vinegar Bottle,Pastry Brush,Cookie Cutter,Muffin Tin,Cake Tin,Mortar,Pestle,Window Squeegee,Microfiber Cloth,Duster,Pruning Shears,Garden Gloves,Seed Packet,Resistance Band,Knee Pad,Towel Clip,Coin Purse,Perfume Bottle,Nail File,Eye Drops,Badge Holder,Label Maker,Memory Card,Hard Drive,Smartwatch,Humidifier,Dehumidifier,Needle,Thread,Zipper,Boarding Pass,Compass,Desk Organiser,Wrist Rest,Name Tag,Chopstick Rest,Soup Spoon,Skewer,Freezer Bag,Cling Wrap,Baking Paper,Kitchen Torch,Espresso Cup,Sugar Bowl,Cheese Grater,Butter Knife,Melon Baller,Tea Infuser,Meat Thermometer,Splatter Guard,Silicone Mat,Drawer Divider,Overdoor Hook,Cable Tie,Velcro Strap,Screen Cloth,Card Reader,Tripod,Phone Stand,Tablet Stand,Lens Cap,Charging Dock,Sim Ejector,Packing Strap,Toiletry Bag,Shoe Bag,Collapsible Cup,Travel Lock,Vacuum Bag,Garment Bag,Document Sleeve,Magnetic Clip,Page Flag,Letter Opener,Desk Mat,Monitor Stand,Laptop Sleeve'.split(',');
const PREFIX=['Small','Large','Mini','Travel','Reusable','Foldable','Silicone','Metal','Wooden','Plastic','Glass','Desk','Kitchen','Bathroom','Laundry','Garden','Office','Travel','Storage','Cleaning'];
const BASE=['Box','Bag','Basket','Bottle','Jar','Clip','Holder','Stand','Tray','Mat','Brush','Sponge','Cloth','Case','Pouch','Container','Rack','Hook','Cover','Pad','Strap','Sleeve','Cable','Adapter','Cup','Bowl','Scoop','Scraper','Dispenser','Organiser'];
const GENERATED=[]; for(const p of PREFIX) for(const b of BASE) GENERATED.push(`${p} ${b}`);
const LIB={easy:EASY,normal:NORMAL,hard:HARD,all:[...new Set([...EASY,...NORMAL,...HARD,...GENERATED])]};
let stats=loadStats(), state=null, canvases=[], ctxs=[], histories=[], redos=[], activeCanvas=0, drawing=false, last=null, audioCtx=null;
function loadStats(){return Object.assign({gamesPlayed:0,totalScore:0,bestScore:0,bestEasy:0,bestNormal:0,bestHard:0,bestDaily:0,lastDifficulty:'normal',muted:false,volume:.35,dailyDoneDate:'',dailyBestToday:0},JSON.parse(localStorage.getItem('shorthandSketchStats')||'{}'))}
function saveStats(){localStorage.setItem('shorthandSketchStats',JSON.stringify(stats))}
function show(id){$$('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active')}
function rand(seed){let x=seed|0;return()=>{x=(x*1664525+1013904223)>>>0;return x/4294967296}}
function dateSeed(){return +new Date().toISOString().slice(0,10).replaceAll('-','')}
function pickObjects(diff,daily){const pools=daily?LIB.all:DIFFICULTY[diff].pools.flatMap(p=>LIB[p]);const arr=[...new Set(pools)];const r=daily?rand(dateSeed()):Math.random;for(let i=arr.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[arr[i],arr[j]]=[arr[j],arr[i]]}return arr.slice(0,10)}
function beep(freq=520,dur=.08,type='sine',vol=.08){if(stats.muted)return;audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=Math.max(.001,stats.volume*vol);o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}
function sound(n){const m={click:[420,.05,'triangle'],count:[520,.12,'sine'],go:[760,.16,'triangle'],ok:[900,.09,'sine'],bad:[180,.11,'sawtooth'],done:[650,.14,'triangle']};const a=m[n]||m.click;beep(...a)}
function speak(text,rate){return new Promise(res=>{if(!('speechSynthesis'in window)){setTimeout(res,700);return}const u=new SpeechSynthesisUtterance(text);u.rate=rate;u.pitch=1.02;u.volume=stats.muted?0:Math.min(1,stats.volume+.25);u.onend=res;u.onerror=res;speechSynthesis.cancel();speechSynthesis.speak(u)})}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function updateStats(){const today=new Date().toISOString().slice(0,10);$('#gamesPlayed').textContent=stats.gamesPlayed;$('#bestScore').textContent=`${stats.bestScore}/10`;$('#averageScore').textContent=stats.gamesPlayed?`${Math.round(stats.totalScore/(stats.gamesPlayed*10)*100)}%`:'0%';$('#bestDaily').textContent=`${stats.bestDaily}/10`;$('#bestEasy').textContent=`${stats.bestEasy}/10`;$('#bestNormal').textContent=`${stats.bestNormal}/10`;$('#bestHard').textContent=`${stats.bestHard}/10`;$('#dailyStatus').textContent=stats.dailyDoneDate===today?'done':'ready';$('#muteBtn').textContent=stats.muted?'🔇':'🔊';$('#difficultySelect').value=stats.lastDifficulty;$('#volumeSlider').value=stats.volume}
function setupCanvases(){const grid=$('#canvasGrid');grid.innerHTML='';canvases=[];ctxs=[];histories=[];redos=[];for(let i=0;i<10;i++){const box=document.createElement('div');box.className='draw-box';box.innerHTML=`<span class="box-num">${i+1}</span><canvas aria-label="Sketch box ${i+1}"></canvas>`;grid.appendChild(box);const c=box.querySelector('canvas');canvases.push(c);histories.push([]);redos.push([]);['pointerdown','pointermove','pointerup','pointercancel','pointerleave'].forEach(e=>c.addEventListener(e,draw));requestAnimationFrame(()=>{resizeCanvas(i);saveHistory(i)})}}
function resizeCanvas(i){const c=canvases[i];if(!c)return;const old=document.createElement('canvas');old.width=c.width;old.height=c.height;if(c.width)old.getContext('2d').drawImage(c,0,0);const r=c.getBoundingClientRect(),dpr=Math.max(1,window.devicePixelRatio||1);c.width=Math.max(1,Math.floor(r.width*dpr));c.height=Math.max(1,Math.floor(r.height*dpr));ctxs[i]=c.getContext('2d');ctxs[i].lineCap='round';ctxs[i].lineJoin='round';if(old.width)ctxs[i].drawImage(old,0,0,c.width,c.height)}
function point(e,c){const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}}
function draw(e){const c=e.currentTarget,i=canvases.indexOf(c);if(state?.phase==='drawing'&&i!==activeCanvas)return;e.preventDefault();if(e.type==='pointerdown'){drawing=true;last=point(e,c);c.setPointerCapture(e.pointerId);saveHistory(i);return}if(!drawing)return;if(e.type==='pointermove'){const p=point(e,c),ctx=ctxs[i];ctx.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over';ctx.strokeStyle=state.color;ctx.lineWidth=state.size*(window.devicePixelRatio||1);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p}else{drawing=false;redos[i]=[]}}
function saveHistory(i){try{histories[i].push(canvases[i].toDataURL());if(histories[i].length>35)histories[i].shift()}catch{}}
function restore(i,data){const img=new Image();img.onload=()=>{ctxs[i].clearRect(0,0,canvases[i].width,canvases[i].height);ctxs[i].drawImage(img,0,0,canvases[i].width,canvases[i].height)};img.src=data}
function undo(){const i=activeCanvas;if(histories[i]?.length>1){redos[i].push(canvases[i].toDataURL());histories[i].pop();restore(i,histories[i].at(-1));sound('click')}}
function redo(){const i=activeCanvas,d=redos[i]?.pop();if(d){saveHistory(i);restore(i,d);sound('click')}}
function clearCanvas(i){saveHistory(i);ctxs[i].clearRect(0,0,canvases[i].width,canvases[i].height);redos[i]=[];sound('click')}
async function countdown(){show('#countdownScreen');for(const t of ['3','2','1','GO']){$('#countdownText').textContent=t;$('#countdownText').style.animation='none';$('#countdownText').offsetHeight;$('#countdownText').style.animation='pop .72s ease both';sound(t==='GO'?'go':'count');await wait(t==='GO'?650:820)}}
async function startGame(){const daily=$('#dailyModeBtn').classList.contains('active');const diff=daily?'normal':$('#difficultySelect').value;stats.lastDifficulty=diff;saveStats();state={daily,difficulty:diff,objects:pickObjects(diff,daily),phase:'drawing',tool:'pen',color:'#2d2430',size:+$('#sizeSlider').value,answers:[]};setupCanvases();await countdown();show('#drawScreen');await drawingPhase();buildGuess();show('#guessScreen')}
async function drawingPhase(){const cfg=DIFFICULTY[state.difficulty];for(let i=0;i<10;i++){activeCanvas=i;$$('.draw-box').forEach((b,n)=>b.classList.toggle('active',n===i));$('#roundLabel').textContent=`${i+1} / 10`;$('#boxStatus').textContent=`Box ${i+1}`;$('#drawStatus').textContent=`Listen carefully. Number ${i+1} is spoken once.`;canvases[i].scrollIntoView({behavior:'smooth',block:'center'});await speak(`Number ${i+1}. ${state.objects[i]}.`,cfg.rate);await wait(cfg.pause);const secs=cfg.min+Math.random()*(cfg.max-cfg.min),end=performance.now()+secs*1000;$('#drawStatus').textContent=`Sketch now. ${Math.round(secs)} seconds.`;while(performance.now()<end){$('#timerText').textContent=((end-performance.now())/1000).toFixed(1)+'s';await wait(60)}sound('done')}state.phase='guessing';$$('.draw-box').forEach(b=>b.classList.remove('active'));$('#timerText').textContent='0.0s'}
function buildGuess(){const f=$('#guessForm');f.innerHTML='';for(let i=0;i<10;i++){const row=document.createElement('div');row.className='guess-row';row.innerHTML=`<label for="ans${i}">${i+1}</label><input id="ans${i}" autocomplete="off" placeholder="Your answer">`;f.appendChild(row)}setTimeout(()=>$('#ans0')?.focus(),80)}
function norm(s){return(s||'').toLowerCase().replace(/&/g,'and').replace(/ipad/g,'tablet').replace(/[^a-z0-9]/g,'').replace(/s$/,'')}
function lev(a,b){const m=Array.from({length:b.length+1},(_,i)=>[i]);for(let j=0;j<=a.length;j++)m[0][j]=j;for(let i=1;i<=b.length;i++)for(let j=1;j<=a.length;j++)m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1]+1,m[i][j-1]+1,m[i-1][j]+1);return m[b.length][a.length]}
function correct(ans,obj){const a=norm(ans),c=norm(obj);if(!a)return false;if(a===c||a.includes(c)||c.includes(a))return true;return lev(a,c)<=Math.max(1,Math.floor(c.length*.18))}
function submit(){state.answers=Array.from({length:10},(_,i)=>$(`#ans${i}`).value.trim());const results=state.objects.map((o,i)=>correct(state.answers[i],o)),score=results.filter(Boolean).length;stats.gamesPlayed++;stats.totalScore+=score;stats.bestScore=Math.max(stats.bestScore,score);const k='best'+state.difficulty[0].toUpperCase()+state.difficulty.slice(1);stats[k]=Math.max(stats[k],score);if(state.daily){stats.bestDaily=Math.max(stats.bestDaily,score);stats.dailyDoneDate=new Date().toISOString().slice(0,10);stats.dailyBestToday=Math.max(stats.dailyBestToday||0,score)}saveStats();showResults(score,results)}
function showResults(score,results){const pct=Math.round(score*10);$('#resultTitle').textContent=score===10?'Memory Master':score>=8?'Fantastic Recall':score>=6?'Almost There':'Keep Sketching';$('#scoreText').textContent=`${score}/10`;$('#percentText').textContent=`${pct}%`;$('#answerReview').innerHTML='';state.objects.forEach((o,i)=>{const r=document.createElement('div');r.className='review-row';r.innerHTML=`<strong>${i+1}</strong><span><b>${o}</b></span><span class="player-answer">${state.answers[i]||'—'}</span><strong class="${results[i]?'ok':'no'}">${results[i]?'✓':'×'}</strong>`;$('#answerReview').appendChild(r);sound(results[i]?'ok':'bad')});updateStats();show('#resultsScreen')}
function setupPalette(){['#2d2430','#6f586d','#bb777f','#6a9f98','#cf9b3e','#46698e'].forEach(col=>{const b=document.createElement('button');b.className='swatch';b.style.background=col;b.type='button';b.onclick=()=>{if(state)state.color=col;sound('click')};$('#palette').appendChild(b)})}
function wire(){setupPalette();$('#startBtn').onclick=startGame;$('#classicModeBtn').onclick=()=>{$('#classicModeBtn').classList.add('active');$('#dailyModeBtn').classList.remove('active');$('#difficultySelect').disabled=false;sound('click')};$('#dailyModeBtn').onclick=()=>{$('#dailyModeBtn').classList.add('active');$('#classicModeBtn').classList.remove('active');$('#difficultySelect').disabled=true;sound('click')};$('#difficultySelect').onchange=e=>{stats.lastDifficulty=e.target.value;saveStats()};$('#muteBtn').onclick=()=>{stats.muted=!stats.muted;saveStats();updateStats()};$('#volumeSlider').oninput=e=>{stats.volume=+e.target.value;saveStats()};$$('.tool-btn').forEach(b=>b.onclick=()=>{$$('.tool-btn').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.tool=b.dataset.tool;sound('click')});$('#sizeSlider').oninput=e=>{if(state)state.size=+e.target.value};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#clearBoxBtn').onclick=()=>clearCanvas(activeCanvas);$('#clearAllBtn').onclick=()=>canvases.forEach((_,i)=>clearCanvas(i));$('#submitBtn').onclick=submit;$('#guessForm').onsubmit=e=>{e.preventDefault();submit()};$('#playAgainBtn').onclick=startGame;$('#homeBtn').onclick=()=>{if('speechSynthesis'in window)speechSynthesis.cancel();updateStats();show('#homeScreen')};window.addEventListener('resize',()=>canvases.forEach((_,i)=>resizeCanvas(i)))}
wire();updateStats();
