'use strict';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const screens = { home: $('#homeScreen'), countdown: $('#countdownScreen'), draw: $('#drawScreen'), guess: $('#guessScreen'), result: $('#resultScreen') };
const colors = ['#253048','#c93f60','#13935f','#3377bd','#7458d5','#ef9f4d'];
const settings = {
  easy: { min: 6, max: 7, rate: 0.68, pause: 1150, label: 'Easy' },
  normal: { min: 5, max: 6, rate: 0.74, pause: 1000, label: 'Normal' },
  hard: { min: 3, max: 4, rate: 0.82, pause: 850, label: 'Hard' }
};
const categories = {
  easy: ['chair','mug','fork','wallet','toothbrush','backpack','umbrella','spoon','plate','bowl','pillow','blanket','lamp','clock','mirror','comb','soap','towel','broom','bucket','kettle','toaster','pan','knife','glass','bottle','pen','pencil','ruler','notebook','scissors','tape','glue','calendar','folder','keyboard','mouse','charger','phone','watch','socks','shoes','cap','shirt','jacket','key','hanger','fan','book','basket','cushion','rug','curtain','vase','tray','sponge','mop','camera','remote control'],
  normal: ['headphones','stapler','lunch box','hairdryer','water bottle','paperclip','clipboard','calculator','envelope','marker','highlighter','extension cord','power bank','laptop sleeve','screen cleaner','mousepad','desk lamp','sticky notes','binder clip','hole punch','trash bag','dish rack','chopping board','rolling pin','measuring cup','spatula','ladle','peeler','grater','whisk','rice cooker','thermos','food container','can opener','bottle opener','ice tray','oven mitt','apron','laundry basket','iron','razor','toothpaste','nail clipper','tweezers','deodorant','bandage','thermometer','yoga mat','dumbbell','skipping rope','helmet','sunglasses','passport','luggage tag','travel pillow','eye mask','bookmark','whiteboard eraser','desk calendar'],
  hard: ['colander','lint roller','staple remover','cable organiser','garlic press','shoehorn','tea strainer','lemon squeezer','nutcracker','pastry brush','knife block','cutlery tray','funnel','sink strainer','drawer divider','suction cup','shower squeegee','contact lens case','curling iron','straightener','ethernet cable','travel adapter','sim pin','tripod stand','selfie stick','lens cap','packing cube','toiletry bag','bottle brush','straw brush','milk frother','coffee scoop','spice rack','napkin holder','bread bin','fridge magnet','magnetic clip','mason jar','ice bucket','trivet','pot holder','pan lid','drain stopper','robe hook','curtain ring','blind cord','light switch','lampshade','resistance band','foam roller','ankle weight','protein shaker','cork board','label maker','accordion folder','letter opener']
};
const extraObjects = ['air fryer','alarm clock','ashtray','bath mat','bike pump','bird feeder','biscuit tin','blind','brooch','cake stand','cash box','chalk','chalkboard','clothes peg','coffee filter','coin jar','coin pouch','compact mirror','cookie cutter','cooler box','coupon card','cream jug','desk mat','detergent box','dish basin','doorbell','doormat','doorstop','duffle bag','egg tray','fairy light','flashlight','floor lamp','flower pot','foam brush','fruit basket','garden hose','gift bag','grocery bag','hair clip','hair tie','hand cream','hand fan','hand sanitiser','hdmi cable','hot plate','humidifier','ice pack','incense diffuser','index card','ink pad','jar opener','jewellery box','keychain','lanyard','laundry peg','letter tray','lip balm','magnifying glass','makeup brush','makeup pouch','map','matchbox','measuring spoon','memory card','microwave','milk carton','modem','mortar and pestle','music box','napkin ring','night light','oil bottle','ornament','paint brush','paper cup','paper plate','password book','pepper grinder','photo frame','picnic mat','piggy bank','pizza cutter','plant pot','plastic cup','plug adapter','plunger','portable fan','postcard','power strip','push pin','raincoat','recipe card','receipt','report cover','rice paddle','ribbon','router','rubber band','rubber stamp','salad bowl','salt shaker','sandpaper','sauce bottle','saucer','screen protector','scrub brush','seed packet','serving spoon','sewing needle','shoe brush','shoe polish','shopping basket','shower cap','shower curtain','skewer','soap dish','soap pump','softener bottle','soup bowl','spice jar','spray bottle','stamp pad','storage box','storage jar','straw','sugar jar','table lamp','tablecloth','tea cup','tea tin','ticket wallet','tie clip','tissue box','toilet brush','toilet roll','toolbox','torch','tote bag','trash bin','tumbler','usb drive','vinegar bottle','wall hook','webcam','wet wipes','window wiper','wrapping paper','zipper pouch'];
const objectPool = [...new Set([...categories.easy, ...categories.normal, ...categories.hard, ...extraObjects])];
const state = { difficulty: localStorage.lastDifficulty || 'normal', items: [], current: 0, tool: 'pen', color: colors[0], size: 5, boxes: [], drawing: false, muted: localStorage.muted === 'true', score: 0, timer: null, timeLeft: 0 };
const defaultStats = { games: 0, total: 0, best: 0, easy: 0, normal: 0, hard: 0 };
let stats = { ...defaultStats, ...JSON.parse(localStorage.sketchStats || '{}') };
function saveStats(){ localStorage.sketchStats = JSON.stringify(stats); }
function show(name){ Object.values(screens).forEach(s => s.classList.remove('active')); screens[name].classList.add('active'); }
function updateStats(){ $('#gamesPlayed').textContent = stats.games; $('#bestScore').textContent = stats.best; $('#averageScore').textContent = stats.games ? (stats.total / stats.games).toFixed(1) : '0'; }
function beep(freq=500, dur=.08, type='sine', gain=.045){ if(state.muted) return; const ctx = new (window.AudioContext || window.webkitAudioContext)(); const osc = ctx.createOscillator(); const vol = ctx.createGain(); osc.type=type; osc.frequency.value=freq; vol.gain.value=gain; osc.connect(vol); vol.connect(ctx.destination); osc.start(); osc.stop(ctx.currentTime+dur); }
function speak(text, rate){ return new Promise(resolve => { if(state.muted || !('speechSynthesis' in window)){ setTimeout(resolve, 900); return; } speechSynthesis.cancel(); const u = new SpeechSynthesisUtterance(text); u.lang = 'en-US'; u.rate = rate; u.pitch = 1.02; u.volume = .95; const voices = speechSynthesis.getVoices(); const preferred = voices.find(v => /Google US English|Samantha|Microsoft Aria|English/i.test(v.name)); if(preferred) u.voice = preferred; u.onend = resolve; u.onerror = resolve; speechSynthesis.speak(u); }); }
function shuffle(arr){ const a=[...arr]; for(let i=a.length-1;i>0;i--){ const j=Math.floor(Math.random()*(i+1)); [a[i],a[j]]=[a[j],a[i]]; } return a; }
function chooseItems(){ const pool = state.difficulty==='easy' ? [...categories.easy, ...categories.normal.slice(0,15)] : state.difficulty==='hard' ? [...categories.hard, ...categories.normal.slice(10)] : [...categories.normal, ...categories.easy.slice(0,20), ...categories.hard.slice(0,15)]; return shuffle(pool).slice(0,10); }
function createPalette(){ $('#palette').innerHTML=''; colors.forEach(c=>{ const b=document.createElement('button'); b.className='swatch'+(c===state.color?' selected':''); b.style.background=c; b.type='button'; b.onclick=()=>{ state.color=c; state.tool='pen'; updateTools(); beep(660,.04); }; $('#palette').appendChild(b); }); }
function updateTools(){ $('#penBtn').classList.toggle('active', state.tool==='pen'); $('#eraserBtn').classList.toggle('active', state.tool==='eraser'); $$('.swatch').forEach((s,i)=>s.classList.toggle('selected', colors[i]===state.color)); }
function makeCanvasGrid(){ const grid=$('#canvasGrid'); grid.innerHTML=''; state.boxes=[]; for(let i=0;i<10;i++){ const card=document.createElement('div'); card.className='sketch-card'; card.innerHTML=`<p class="card-num">${i+1}</p><canvas aria-label="Sketch box ${i+1}"></canvas>`; grid.appendChild(card); const canvas=card.querySelector('canvas'); const ctx=canvas.getContext('2d'); state.boxes.push({card,canvas,ctx}); attachDraw(canvas,ctx); resizeCanvas(canvas,ctx); } highlightActive(); }
function resizeCanvas(canvas, ctx){ const url = canvas.width ? canvas.toDataURL() : null; const rect = canvas.getBoundingClientRect(); const ratio = Math.max(1, window.devicePixelRatio || 1); canvas.width = Math.max(220, Math.floor(rect.width * ratio)); canvas.height = Math.max(180, Math.floor(rect.height * ratio)); ctx.setTransform(ratio,0,0,ratio,0,0); ctx.lineCap='round'; ctx.lineJoin='round'; if(url){ const img=new Image(); img.onload=()=>ctx.drawImage(img,0,0,rect.width,rect.height); img.src=url; } }
function pos(e, canvas){ const r=canvas.getBoundingClientRect(); const p=e.touches ? e.touches[0] : e; return {x:p.clientX-r.left,y:p.clientY-r.top}; }
function attachDraw(canvas,ctx){ let last=null; const down=e=>{ e.preventDefault(); state.drawing=true; last=pos(e,canvas); beep(240,.025,'triangle',.018); }; const move=e=>{ if(!state.drawing) return; e.preventDefault(); const p=pos(e,canvas); ctx.globalCompositeOperation = state.tool==='eraser' ? 'destination-out' : 'source-over'; ctx.strokeStyle = state.color; ctx.lineWidth = state.size; ctx.beginPath(); ctx.moveTo(last.x,last.y); ctx.lineTo(p.x,p.y); ctx.stroke(); last=p; }; const up=()=>{ state.drawing=false; last=null; ctx.globalCompositeOperation='source-over'; }; canvas.addEventListener('mousedown',down); canvas.addEventListener('mousemove',move); window.addEventListener('mouseup',up); canvas.addEventListener('touchstart',down,{passive:false}); canvas.addEventListener('touchmove',move,{passive:false}); window.addEventListener('touchend',up); }
function clearCanvas(box){ const rect=box.canvas.getBoundingClientRect(); box.ctx.clearRect(0,0,rect.width,rect.height); }
function highlightActive(){ state.boxes.forEach((b,i)=>b.card.classList.toggle('active', i===state.current)); $('#drawProgress').textContent=`${Math.min(state.current+1,10)} / 10`; $('#activeBoxLabel').textContent=`Box ${Math.min(state.current+1,10)}`; $('#listenText').textContent=`Listen: number ${Math.min(state.current+1,10)}`; }
async function countdown(){ show('countdown'); for(const t of ['3','2','1','GO']){ $('#countdownText').textContent=t; $('#countdownText').style.animation='none'; void $('#countdownText').offsetWidth; $('#countdownText').style.animation='pop .85s ease both'; beep(t==='GO'?740:420,.13,'sine',.06); await new Promise(r=>setTimeout(r,780)); } }
async function startGame(){ state.items=chooseItems(); state.current=0; makeCanvasGrid(); await countdown(); show('draw'); await runDrawingPhase(); }
async function runDrawingPhase(){ const cfg=settings[state.difficulty]; for(let i=0;i<10;i++){ state.current=i; highlightActive(); const item=state.items[i]; const spoken = `Number ${i+1}. The word is. ${item}.`; await speak(spoken, cfg.rate); await new Promise(r=>setTimeout(r,cfg.pause)); const seconds = cfg.min + Math.random()*(cfg.max-cfg.min); await drawTimer(seconds); } roundDone(); }
function drawTimer(seconds){ return new Promise(resolve=>{ state.timeLeft=seconds; clearInterval(state.timer); state.timer=setInterval(()=>{ state.timeLeft-=.1; $('#timerText').textContent=Math.max(0,state.timeLeft).toFixed(1)+'s'; if(state.timeLeft<=0){ clearInterval(state.timer); beep(520,.06); resolve(); } },100); }); }
function roundDone(){ beep(660,.08); setTimeout(()=>beep(880,.12),120); buildGuess(); show('guess'); }
function buildGuess(){ const drawings=$('#guessDrawingList'); const answers=$('#answerList'); drawings.innerHTML=''; answers.innerHTML=''; state.boxes.forEach((b,i)=>{ const thumb=document.createElement('div'); thumb.className='guess-thumb'; thumb.innerHTML=`<p class="card-num">${i+1}</p><img src="${b.canvas.toDataURL('image/png')}" alt="Your sketch ${i+1}">`; drawings.appendChild(thumb); const row=document.createElement('div'); row.className='answer-row'; row.innerHTML=`<label for="answer${i}">${i+1}</label><input id="answer${i}" autocomplete="off" placeholder="Your guess...">`; answers.appendChild(row); }); $('#answer0')?.focus(); }
function normalise(s){ return (s||'').toLowerCase().trim().replace(/&/g,'and').replace(/[-_]/g,' ').replace(/[^a-z0-9 ]/g,'').replace(/\s+/g,' ').replace(/\b(one|a|an|the)\b/g,'').replace(/s$/,'').trim(); }
function levenshtein(a,b){ const dp=Array.from({length:a.length+1},(_,i)=>[i]); for(let j=1;j<=b.length;j++) dp[0][j]=j; for(let i=1;i<=a.length;i++) for(let j=1;j<=b.length;j++) dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]:1+Math.min(dp[i-1][j],dp[i][j-1],dp[i-1][j-1]); return dp[a.length][b.length]; }
function isCorrect(answer, correct){ const a=normalise(answer), c=normalise(correct); if(!a) return false; if(a===c) return true; if(a.replace(/ /g,'')===c.replace(/ /g,'')) return true; const aliases={ 'tooth brush':'toothbrush','sun glasses':'sunglasses','sunglass':'sunglasses','remote':'remote control','remotecontrol':'remote control','shoe horn':'shoehorn','lunchbox':'lunch box','waterbottle':'water bottle','hair dryer':'hairdryer','ear phones':'earbuds','earphone':'earbuds','ipad':'tablet' }; if(normalise(aliases[a])===c) return true; return levenshtein(a,c)<=Math.max(1,Math.floor(c.length*.18)); }
function checkAnswers(){ let score=0; const resultRows=[]; for(let i=0;i<10;i++){ const ans=$(`#answer${i}`).value; const correct=state.items[i]; const ok=isCorrect(ans,correct); if(ok) score++; resultRows.push({i,ans,correct,ok}); } state.score=score; stats.games++; stats.total+=score; stats.best=Math.max(stats.best,score); stats[state.difficulty]=Math.max(stats[state.difficulty]||0,score); saveStats(); updateStats(); buildResults(resultRows); beep(score>=7?880:360,.12,score>=7?'sine':'sawtooth',.05); if(score>=7) setTimeout(()=>beep(1100,.16,'sine',.045),130); show('result'); }
function buildResults(rows){ const pct=Math.round(state.score*10); $('#scoreText').textContent=`${state.score} / 10`; $('#percentText').textContent=`${pct}%`; $('#resultTitle').textContent= state.score===10?'Memory Master':state.score>=8?'Fantastic Recall':state.score>=5?'Almost There':'Keep Sketching'; const list=$('#resultList'); list.innerHTML=''; rows.forEach(r=>{ const row=document.createElement('div'); row.className='result-row'; row.innerHTML=`<b>${r.i+1}</b><span>Correct: <strong>${r.correct}</strong></span><span>Your answer: <strong>${r.ans || '—'}</strong></span><i class="${r.ok?'ok':'bad'}">${r.ok?'✓':'✕'}</i>`; list.appendChild(row); }); }
function bind(){ $('#startBtn').onclick=()=>{beep(640,.07); startGame();}; $('#submitBtn').onclick=checkAnswers; $('#playAgainBtn').onclick=startGame; $('#homeBtn').onclick=()=>show('home'); $('#muteBtn').onclick=()=>{ state.muted=!state.muted; localStorage.muted=String(state.muted); $('#muteBtn').textContent=state.muted?'🔇':'🔊'; }; $('#penBtn').onclick=()=>{state.tool='pen'; updateTools();}; $('#eraserBtn').onclick=()=>{state.tool='eraser'; updateTools();}; $('#clearBoxBtn').onclick=()=>clearCanvas(state.boxes[state.current]); $('#clearAllBtn').onclick=()=>{ if(confirm('Clear all sketch boxes?')) state.boxes.forEach(clearCanvas); }; $('#thicknessRange').oninput=e=>state.size=Number(e.target.value); $('#difficultyPanel').onclick=e=>{ const btn=e.target.closest('button[data-difficulty]'); if(!btn) return; state.difficulty=btn.dataset.difficulty; localStorage.lastDifficulty=state.difficulty; $$('#difficultyPanel button').forEach(b=>b.classList.toggle('selected',b===btn)); beep(560,.04); }; window.addEventListener('resize',()=>state.boxes.forEach(b=>resizeCanvas(b.canvas,b.ctx))); document.addEventListener('keydown',e=>{ if(e.key==='Enter' && screens.guess.classList.contains('active')) checkAnswers(); }); }
function init(){ bind(); createPalette(); updateTools(); updateStats(); $('#muteBtn').textContent=state.muted?'🔇':'🔊'; $$('#difficultyPanel button').forEach(b=>b.classList.toggle('selected',b.dataset.difficulty===state.difficulty)); if('speechSynthesis' in window) speechSynthesis.onvoiceschanged=()=>speechSynthesis.getVoices(); }
init();
