 'use strict';
const EASY_OBJECTS = ['Chair', 'Table', 'Mug', 'Cup', 'Plate', 'Bowl', 'Spoon', 'Fork', 'Knife', 'Glass', 'Bottle', 'Water Bottle', 'Lunch Box', 'Wallet', 'Key', 'Phone', 'Book', 'Notebook', 'Pen', 'Pencil', 'Eraser', 'Ruler', 'Scissors', 'Tape', 'Glue Stick', 'Paper Clip', 'Stapler', 'Envelope', 'Folder', 'Bag', 'Backpack', 'Umbrella', 'Hat', 'Cap', 'Shirt', 'Sock', 'Shoe', 'Slipper', 'Jacket', 'Belt', 'Watch', 'Clock', 'Mirror', 'Comb', 'Hairbrush', 'Toothbrush', 'Toothpaste', 'Soap', 'Shampoo Bottle', 'Towel', 'Tissue Box', 'Wet Wipes', 'Basket', 'Laundry Basket', 'Hanger', 'Iron', 'Pillow', 'Blanket', 'Lamp', 'Candle', 'Vase', 'Remote Control', 'Keyboard', 'Mouse', 'Laptop', 'Charger', 'Headphones', 'Camera', 'Fan', 'Flashlight', 'Battery', 'Light Bulb', 'Trash Can', 'Broom', 'Mop', 'Bucket', 'Dustpan', 'Sponge', 'Spray Bottle', 'Doormat', 'Cushion', 'Tray', 'Coaster', 'Shopping Bag', 'Reusable Bag'];
const NORMAL_OBJECTS = ['Chair', 'Table', 'Mug', 'Cup', 'Plate', 'Bowl', 'Spoon', 'Fork', 'Knife', 'Glass', 'Bottle', 'Water Bottle', 'Lunch Box', 'Wallet', 'Key', 'Phone', 'Book', 'Notebook', 'Pen', 'Pencil', 'Eraser', 'Ruler', 'Scissors', 'Tape', 'Glue Stick', 'Paper Clip', 'Stapler', 'Envelope', 'Folder', 'Bag', 'Backpack', 'Umbrella', 'Hat', 'Cap', 'Shirt', 'Sock', 'Shoe', 'Slipper', 'Jacket', 'Belt', 'Watch', 'Clock', 'Mirror', 'Comb', 'Hairbrush', 'Toothbrush', 'Toothpaste', 'Soap', 'Shampoo Bottle', 'Towel', 'Tissue Box', 'Wet Wipes', 'Basket', 'Laundry Basket', 'Hanger', 'Iron', 'Pillow', 'Blanket', 'Lamp', 'Candle', 'Vase', 'Remote Control', 'Keyboard', 'Mouse', 'Laptop', 'Charger', 'Headphones', 'Camera', 'Fan', 'Flashlight', 'Battery', 'Light Bulb', 'Trash Can', 'Broom', 'Mop', 'Bucket', 'Dustpan', 'Sponge', 'Spray Bottle', 'Doormat', 'Cushion', 'Tray', 'Coaster', 'Shopping Bag', 'Reusable Bag', 'Desk Lamp', 'Highlighter', 'Marker', 'Whiteboard', 'Clipboard', 'Binder', 'Sticky Note', 'Push Pin', 'Rubber Band', 'Binder Clip', 'Calculator', 'Printer', 'USB Drive', 'Hard Drive', 'Power Bank', 'Speaker', 'Earbuds', 'Tablet', 'Monitor', 'Cable', 'Power Strip', 'Extension Cord', 'Webcam', 'Microphone', 'Router', 'Calendar', 'Planner', 'Bookmark', 'Magazine', 'Picture Frame', 'Curtain', 'Rug', 'Storage Box', 'Drawer', 'Shelf', 'Hook', 'Padlock', 'Doorbell', 'Door Stop', 'Suitcase', 'Passport', 'Travel Pillow', 'Luggage Tag', 'Travel Adapter', 'Toiletry Bag', 'Eye Mask', 'Ear Plug', 'Thermos', 'Food Container', 'Jar', 'Can', 'Carton', 'Cereal Box', 'Chip Bag', 'Bread Bag', 'Egg Carton', 'Tea Bag', 'Kettle', 'Teapot', 'Frying Pan', 'Saucepan', 'Pot', 'Lid', 'Cutting Board', 'Strainer', 'Peeler', 'Whisk', 'Spatula', 'Tongs', 'Ladle', 'Measuring Cup', 'Rolling Pin', 'Can Opener', 'Bottle Opener', 'Oven Mitt', 'Apron', 'Dish Rack', 'Dish Soap', 'Vacuum Cleaner', 'Duster', 'Toilet Brush', 'Plunger', 'Bath Mat', 'Shower Cap', 'Hair Tie', 'Hair Clip', 'Nail Clipper', 'Nail File', 'Cotton Bud', 'Cotton Pad', 'Hand Sanitiser', 'Face Mask', 'Bandage', 'Thermometer', 'Medicine Bottle', 'Pill Box', 'Sunglasses', 'Glasses Case', 'Card Holder', 'Coin Purse', 'Makeup Brush', 'Lip Balm', 'Lotion Bottle', 'Sunscreen', 'Perfume Bottle', 'Yoga Mat', 'Dumbbell', 'Jump Rope', 'Tennis Ball', 'Basketball', 'Soccer Ball', 'Baseball Bat', 'Helmet', 'Whistle', 'Stopwatch', 'Picnic Basket', 'Cooler Bag', 'Ice Pack', 'Garden Hose', 'Watering Can', 'Flower Pot', 'Trowel', 'Rake', 'Shovel', 'Garden Gloves', 'Hammer', 'Screwdriver', 'Wrench', 'Pliers', 'Tape Measure', 'Toolbox', 'Paint Brush'];
const HARD_OBJECTS = ['Colander', 'Grater', 'Garlic Press', 'Potato Masher', 'Salad Spinner', 'Lemon Squeezer', 'Juicer', 'Blender', 'Toaster', 'Rice Cooker', 'Microwave', 'Air Fryer', 'Coffee Grinder', 'French Press', 'Salt Shaker', 'Pepper Grinder', 'Oil Bottle', 'Spice Jar', 'Ice Cube Tray', 'Freezer Bag', 'Cling Wrap', 'Foil Roll', 'Baking Tray', 'Muffin Tin', 'Cookie Cutter', 'Pizza Cutter', 'Ice Cream Scoop', 'Wok', 'Steamer Basket', 'Knife Block', 'Utensil Holder', 'Soap Dispenser', 'Toothbrush Holder', 'Shower Caddy', 'Lint Roller', 'Shoe Horn', 'Shoe Brush', 'Shoe Polish', 'Shoelace', 'Insole', 'Shoe Rack', 'Drying Rack', 'Garment Bag', 'Jewellery Box', 'Ring Box', 'Desk Organiser', 'Pen Cup', 'File Tray', 'Bookend', 'Mouse Pad', 'Staple Remover', 'Hole Punch', 'Correction Tape', 'Name Tag', 'Lanyard', 'Badge Holder', 'Cable Organiser', 'Cable Tie', 'Charging Dock', 'Phone Stand', 'Tablet Stand', 'Stylus', 'Wireless Charger', 'HDMI Cable', 'Card Reader', 'USB Hub', 'Ring Light', 'Night Light', 'Diffuser', 'Room Spray', 'Table Runner', 'Placemat', 'Bag Clip', 'Fridge Magnet', 'Whiteboard Eraser', 'Notice Board', 'Drawer Divider', 'Closet Organiser', 'Vacuum Bag', 'Combination Lock', 'Remote Holder', 'Passport Holder', 'Travel Wallet', 'Packing Cube', 'Travel Bottle', 'Bento Box', 'Condiment Cup', 'Noodle Cup', 'Sauce Packet', 'Coffee Tin', 'Mint Tin', 'Bottle Cap', 'Jar Lid', 'Can Tab', 'Takeaway Box', 'Cup Sleeve', 'Playing Cards', 'Dice', 'Puzzle Piece', 'Score Pad', 'Foam Roller', 'Massage Ball', 'Bike Pump', 'Bike Lock', 'Badminton Racket', 'Shuttlecock', 'Golf Tee', 'Beach Towel', 'Sun Hat', 'Camping Mug', 'Tent Peg', 'Carabiner', 'Mini Torch', 'Picnic Mat', 'Insect Repellent', 'Laptop Sleeve', 'Document Wallet', 'Receipt Holder', 'Letter Opener', 'Paperweight', 'Stress Ball', 'Keyboard Brush', 'Monitor Stand', 'Page Flag', 'Tab Divider', 'Report Cover', 'Projector Remote', 'Desk Bell', 'Plant Mister', 'Plant Saucer', 'Kneeling Pad', 'Seed Tray', 'Soil Scoop'];
const OBJECT_LIBRARY = Array.from(new Set([...EASY_OBJECTS, ...NORMAL_OBJECTS, ...HARD_OBJECTS]));
const DIFFICULTY = { easy: {min:6,max:7,rate:.66,pause:950}, normal: {min:5,max:6,rate:.72,pause:850}, hard: {min:3,max:4,rate:.78,pause:700} };
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const defaultStats = {gamesPlayed:0,totalScore:0,bestScore:0,bestEasy:0,bestNormal:0,bestHard:0,lastDifficulty:'normal',muted:false,volume:.45};
let stats = {...defaultStats, ...JSON.parse(localStorage.getItem('shorthandSketchStats') || '{}')};
let state = null, canvases = [], ctxs = [], activeCanvas = 0, isDrawing = false, lastPoint = null, audioCtx = null;
function saveStats(){ localStorage.setItem('shorthandSketchStats', JSON.stringify(stats)); }
function show(id){ $$('.screen').forEach(s=>s.classList.remove('active')); $(id).classList.add('active'); }
function sound(name='click'){ if(stats.muted) return; try{ audioCtx = audioCtx || new (window.AudioContext||window.webkitAudioContext)(); const map={click:[520,.04],count:[660,.08],go:[880,.12],correct:[760,.1],wrong:[190,.12],complete:[620,.12],celebrate:[880,.15]}; const [f,d]=map[name]||map.click; const o=audioCtx.createOscillator(), g=audioCtx.createGain(); o.frequency.value=f; o.type=name==='wrong'?'sawtooth':'sine'; g.gain.value=.001; o.connect(g); g.connect(audioCtx.destination); const now=audioCtx.currentTime; g.gain.exponentialRampToValueAtTime(Math.max(.015,stats.volume*.08), now+.01); g.gain.exponentialRampToValueAtTime(.001, now+d); o.start(now); o.stop(now+d+.03); }catch(e){} }
function speak(text, rate){ return new Promise(resolve=>{ if(!('speechSynthesis' in window)) return setTimeout(resolve,900); speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text); u.rate=rate; u.pitch=.98; u.volume=stats.muted?0:Math.min(1,stats.volume+.2); const voices=speechSynthesis.getVoices(); const preferred=voices.find(v=>/Google UK English Female|Microsoft Sonia|Samantha|Karen|Daniel|Google US English/i.test(v.name)); if(preferred) u.voice=preferred; u.onend=resolve; u.onerror=resolve; speechSynthesis.speak(u); }); }
function wait(ms){ return new Promise(r=>setTimeout(r,ms)); }
function updateStatsUI(){ $('#gamesPlayed').textContent=stats.gamesPlayed; $('#bestScore').textContent=`${stats.bestScore} / 10`; $('#averageScore').textContent=stats.gamesPlayed?`${Math.round(stats.totalScore/stats.gamesPlayed*10)}%`:'0%'; $('#muteBtn').textContent=stats.muted?'🔇':'🔊'; }
function selectDifficulty(diff){ stats.lastDifficulty=diff; saveStats(); $$('#difficultyPanel button').forEach(b=>b.classList.toggle('selected', b.dataset.difficulty===diff)); }
function pickObjects(diff){ const pool=diff==='easy'?EASY_OBJECTS:diff==='hard'?HARD_OBJECTS:NORMAL_OBJECTS; const picked=[]; while(picked.length<10){ const item=pool[Math.floor(Math.random()*pool.length)]; if(!picked.includes(item)) picked.push(item); } return picked; }
function setupPalette(){ const colors=['#20243a','#c93d5d','#14936a','#2f70bd','#7357d6','#d59c2b']; const pal=$('#palette'); pal.innerHTML=''; colors.forEach((c,i)=>{ const b=document.createElement('button'); b.type='button'; b.className='swatch'+(i===0?' selected':''); b.style.background=c; b.setAttribute('aria-label',`Use colour ${c}`); b.onclick=()=>{ state.color=c; $$('.swatch').forEach(x=>x.classList.remove('selected')); b.classList.add('selected'); sound('click'); }; pal.appendChild(b); }); }
function sliderToLineWidth(value){ const t=Number(value)/100; return +(1.2 + Math.pow(t,1.85)*9.8).toFixed(2); }
function updateThickness(){ const px=sliderToLineWidth($('#thicknessRange').value); if(state) state.size=px; $('#thicknessPreview').style.setProperty('--preview-size', `${px}px`); }
function resizeCanvas(c, keep=true){ const existing=keep && c.width && c.height ? c.toDataURL() : null; const rect=c.getBoundingClientRect(); const ratio=Math.max(1, window.devicePixelRatio || 1); c.width=Math.round(rect.width*ratio); c.height=Math.round(rect.height*ratio); const ctx=c.getContext('2d'); ctx.setTransform(ratio,0,0,ratio,0,0); ctx.lineCap='round'; ctx.lineJoin='round'; ctxs[canvases.indexOf(c)]=ctx; if(existing){ const img=new Image(); img.onload=()=>ctx.drawImage(img,0,0,rect.width,rect.height); img.src=existing; } }
function setupCanvases(){ const grid=$('#canvasGrid'); grid.innerHTML=''; canvases=[]; ctxs=[]; for(let i=0;i<10;i++){ const box=document.createElement('div'); box.className='draw-box'; box.innerHTML=`<span class="box-num">${i+1}</span><canvas aria-label="Drawing box ${i+1}"></canvas>`; grid.appendChild(box); const c=box.querySelector('canvas'); canvases.push(c); c.addEventListener('pointerdown', handlePointer); c.addEventListener('pointermove', handlePointer); c.addEventListener('pointerup', handlePointer); c.addEventListener('pointercancel', handlePointer); c.addEventListener('pointerleave', handlePointer); requestAnimationFrame(()=>resizeCanvas(c,false)); } }
function canvasPoint(e,c){ const r=c.getBoundingClientRect(); return { x:e.clientX-r.left, y:e.clientY-r.top }; }
function handlePointer(e){ const c=e.currentTarget; const i=canvases.indexOf(c); if(state.phase==='drawing' && i!==activeCanvas) return; e.preventDefault(); const ctx=ctxs[i]; if(!ctx) return; if(e.type==='pointerdown'){ isDrawing=true; lastPoint=canvasPoint(e,c); c.setPointerCapture?.(e.pointerId); sound('click'); return; } if(!isDrawing) return; if(e.type==='pointermove'){ const p=canvasPoint(e,c); ctx.globalCompositeOperation=state.tool==='eraser'?'destination-out':'source-over'; ctx.strokeStyle=state.color; ctx.lineWidth=state.size; ctx.beginPath(); ctx.moveTo(lastPoint.x,lastPoint.y); ctx.lineTo(p.x,p.y); ctx.stroke(); lastPoint=p; } else { isDrawing=false; } }
function clearCanvas(i){ const c=canvases[i], r=c.getBoundingClientRect(); ctxs[i].clearRect(0,0,r.width,r.height); }
async function countdown(){ show('#countdownScreen'); for(const t of ['3','2','1','GO']){ $('#countdownText').textContent=t; $('#countdownText').style.animation='none'; void $('#countdownText').offsetWidth; $('#countdownText').style.animation='pop .75s ease both'; sound(t==='GO'?'go':'count'); await wait(t==='GO'?620:780); } }
async function beginGame(){ const diff=stats.lastDifficulty || 'normal'; state={difficulty:diff,objects:pickObjects(diff),phase:'drawing',tool:'pen',color:'#20243a',size:sliderToLineWidth($('#thicknessRange').value),answers:[]}; setupPalette(); setupCanvases(); await countdown(); show('#drawScreen'); await runDrawingPhase(); buildGuessing(); show('#guessScreen'); }
async function runDrawingPhase(){ const cfg=DIFFICULTY[state.difficulty]; for(let i=0;i<10;i++){ activeCanvas=i; $$('.draw-box').forEach((b,idx)=>b.classList.toggle('active',idx===i)); $('#drawProgress').textContent=`${i+1} / 10`; $('#activeBoxLabel').textContent=`Box ${i+1}`; $('#listenText').textContent='Listen carefully'; const spoken=state.objects[i].replace(/([a-z])([A-Z])/g,'$1 $2'); await speak(`Number ${i+1}. Listen carefully. ${spoken}.`, cfg.rate); $('#listenText').textContent='Sketch now'; await wait(cfg.pause); const seconds=cfg.min+Math.random()*(cfg.max-cfg.min); const end=performance.now()+seconds*1000; while(performance.now()<end){ $('#timerText').textContent=Math.max(0,(end-performance.now())/1000).toFixed(1)+'s'; await wait(70); } sound('complete'); } state.phase='guessing'; $$('.draw-box').forEach(b=>b.classList.remove('active')); $('#timerText').textContent='0.0s'; }
function buildGuessing(){ const gd=$('#guessDrawingList'), al=$('#answerList'); gd.innerHTML=''; al.innerHTML=''; canvases.forEach((c,i)=>{ const card=document.createElement('div'); card.className='guess-card'; card.innerHTML=`<span>${i+1}</span><img alt="Your sketch for box ${i+1}" src="${c.toDataURL()}">`; gd.appendChild(card); const row=document.createElement('div'); row.className='answer-row'; row.innerHTML=`<label for="ans${i}">${i+1}</label><input id="ans${i}" autocomplete="off" placeholder="Type your guess">`; al.appendChild(row); }); setTimeout(()=>$('#ans0')?.focus(),80); }
function norm(s){ return (s||'').toLowerCase().replace(/&/g,'and').replace(/ipad/g,'tablet').replace(/[^a-z0-9]/g,'').replace(/s$/,''); }
function distance(a,b){ const m=Array.from({length:b.length+1},(_,i)=>[i]); for(let j=0;j<=a.length;j++) m[0][j]=j; for(let i=1;i<=b.length;i++) for(let j=1;j<=a.length;j++) m[i][j]=b[i-1]===a[j-1]?m[i-1][j-1]:Math.min(m[i-1][j-1]+1,m[i][j-1]+1,m[i-1][j]+1); return m[b.length][a.length]; }
function correct(ans, truth){ const a=norm(ans), c=norm(truth); if(!a) return false; if(a===c||a.includes(c)||c.includes(a)) return true; return distance(a,c)<=Math.max(1,Math.floor(c.length*.18)); }
function submitAnswers(){ state.answers=Array.from({length:10},(_,i)=>$('#ans'+i).value.trim()); const checks=state.objects.map((o,i)=>correct(state.answers[i],o)); const score=checks.filter(Boolean).length; stats.gamesPlayed++; stats.totalScore+=score; stats.bestScore=Math.max(stats.bestScore,score); const k='best'+state.difficulty[0].toUpperCase()+state.difficulty.slice(1); stats[k]=Math.max(stats[k]||0,score); saveStats(); showResults(score,checks); }
function showResults(score,checks){ $('#scoreText').textContent=`${score} / 10`; $('#percentText').textContent=`${score*10}%`; $('#resultTitle').textContent=score===10?'Memory Master':score>=8?'Fantastic Recall':score>=6?'Almost There':'Keep Sketching'; const list=$('#resultList'); list.innerHTML=''; state.objects.forEach((obj,i)=>{ const row=document.createElement('div'); row.className='result-row'; row.innerHTML=`<b>${i+1}</b><span><strong>${obj}</strong></span><span class="player">${state.answers[i]||'—'}</span><b class="${checks[i]?'ok':'no'}">${checks[i]?'✓':'×'}</b>`; list.appendChild(row); }); show('#resultScreen'); sound(score>=8?'celebrate':'complete'); updateStatsUI(); }
function wire(){ $$('#difficultyPanel button').forEach(b=>b.onclick=()=>{ selectDifficulty(b.dataset.difficulty); sound('click'); }); $('#startBtn').onclick=()=>{ sound('click'); beginGame(); }; $('#muteBtn').onclick=()=>{ stats.muted=!stats.muted; saveStats(); updateStatsUI(); }; $('#penBtn').onclick=()=>{ state.tool='pen'; $('#penBtn').classList.add('active'); $('#eraserBtn').classList.remove('active'); sound('click'); }; $('#eraserBtn').onclick=()=>{ state.tool='eraser'; $('#eraserBtn').classList.add('active'); $('#penBtn').classList.remove('active'); sound('click'); }; $('#clearBoxBtn').onclick=()=>{ clearCanvas(activeCanvas); sound('click'); }; $('#clearAllBtn').onclick=()=>{ canvases.forEach((_,i)=>clearCanvas(i)); sound('click'); }; $('#thicknessRange').oninput=updateThickness; $('#submitBtn').onclick=submitAnswers; $('#answerList').onsubmit=e=>{e.preventDefault();submitAnswers();}; $('#playAgainBtn').onclick=()=>{ sound('click'); beginGame(); }; $('#homeBtn').onclick=()=>{ speechSynthesis?.cancel(); show('#homeScreen'); updateStatsUI(); }; window.addEventListener('resize',()=>canvases.forEach(c=>resizeCanvas(c,true))); }
selectDifficulty(stats.lastDifficulty); updateThickness(); setupPalette(); wire(); updateStatsUI();
